### ISSUE TITLE
Could not create Appender...

### ISSUE THREAD

**Issue by dviry** [joelweiss/Log4net.Appender.Serilog#2]
Log4net.Appender.Serilog 1.0.9 
Serilog.AspNetCore 2.1.1
Log4net 2.0.8.0

I am getting the following error on startup after upgrading to latest NuGets:

log4net:ERROR Could not create Appender [SerilogAppender] of type [log4net.Appender.Serilog.SerilogAppender, log4net.Appender.Serilog]. Reported error follows.
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)
log4net:ERROR Appender named [SerilogAppender] not found.

**Comment by klapmalt** [comment]
We encountered the same error while trying to configure the appender in app.config.

Is there a reason why there is no parameterless constructor? The existing constructor has a null default parameter. It seems that Log4net appender initialization expects a parameterless constructor to create the appender.

**Comment by joelweiss** [comment]
Published to [nuget](https://www.nuget.org/packages/Log4net.Appender.Serilog/1.0.11) (the package is still validating, so you might have to wait a few minutes)
